using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Agibuild.Fulora.Bridge.Generator;

/// <summary>
/// Emits the <c>*BridgeRegistration</c> class for <see cref="BridgeDirection.Export"/> interfaces.
/// Each method gets a direct RPC handler — no reflection at runtime.
/// </summary>
internal static class BridgeHostEmitter
{
    private static readonly string[] OptionsParam = ["options"];
    public static string Emit(BridgeInterfaceModel model)
    {
        var sb = new StringBuilder();
        var className = $"{model.ServiceName}BridgeRegistration";
        var ns = model.Namespace;

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable IL2026 // Suppress trim analysis warnings for JSON deserialization in generated bridge code");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Agibuild.Fulora;");
        sb.AppendLine();

        // Assembly attribute
        sb.AppendLine($"[assembly: global::Agibuild.Fulora.BridgeRegistration(typeof({model.InterfaceFullName}), typeof({GetFullClassName(ns, className)}))]");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        var indent = string.IsNullOrEmpty(ns) ? "" : "    ";

        sb.AppendLine($"{indent}[global::System.CodeDom.Compiler.GeneratedCode(\"Agibuild.WebView.BridgeGenerator\", \"1.0.0\")]");
        sb.AppendLine($"{indent}internal sealed class {className} : global::Agibuild.Fulora.IBridgeServiceRegistration<{model.InterfaceFullName}>");
        sb.AppendLine($"{indent}{{");

        // ServiceName
        sb.AppendLine($"{indent}    public string ServiceName => \"{model.ServiceName}\";");
        sb.AppendLine();

        // MethodNames
        sb.Append($"{indent}    public IReadOnlyList<string> MethodNames => new string[] {{ ");
        for (int i = 0; i < model.Methods.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append($"\"{model.Methods[i].RpcMethodName}\"");
        }
        sb.AppendLine(" };");
        sb.AppendLine();

        // EventNames
        if (model.Events.Length > 0)
        {
            sb.Append($"{indent}    public IReadOnlyList<string> EventNames => new string[] {{ ");
            for (int i = 0; i < model.Events.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append($"\"{model.Events[i].CamelCaseName}\"");
            }
            sb.AppendLine(" };");
            sb.AppendLine();
        }

        // RegisterHandlers
        EmitRegisterHandlers(sb, model, indent);
        sb.AppendLine();

        // UnregisterHandlers
        EmitUnregisterHandlers(sb, model, indent);
        sb.AppendLine();

        // DisconnectEvents
        if (model.Events.Length > 0)
        {
            EmitDisconnectEvents(sb, model, indent);
            sb.AppendLine();
        }

        // GetJsStub
        EmitGetJsStub(sb, model, indent);

        sb.AppendLine($"{indent}}}");

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void EmitRegisterHandlers(StringBuilder sb, BridgeInterfaceModel model, string indent)
    {
        sb.AppendLine($"{indent}    public void RegisterHandlers(global::Agibuild.Fulora.IWebViewRpcService rpc, {model.InterfaceFullName} impl)");
        sb.AppendLine($"{indent}    {{");

        foreach (var method in model.Methods)
        {
            if (method.IsAsyncEnumerable)
            {
                EmitStreamingHandler(sb, method, indent);
            }
            else if (method.HasCancellationToken)
            {
                EmitCancellableHandler(sb, method, indent);
            }
            else
            {
                EmitStandardHandler(sb, method, indent);
            }
        }

        foreach (var evt in model.Events)
        {
            EmitEventHandlers(sb, model.ServiceName, evt, indent);
        }

        sb.AppendLine($"{indent}    }}");
    }

    private static void EmitStandardHandler(StringBuilder sb, BridgeMethodModel method, string indent)
    {
        sb.AppendLine($"{indent}        rpc.Handle(\"{method.RpcMethodName}\", async (global::System.Text.Json.JsonElement? __args) =>");
        sb.AppendLine($"{indent}        {{");
        EmitParameterDeserialization(sb, method, indent);
        EmitMethodInvocation(sb, method, indent);
        sb.AppendLine($"{indent}        }});");
    }

    private static void EmitCancellableHandler(StringBuilder sb, BridgeMethodModel method, string indent)
    {
        sb.AppendLine($"{indent}        rpc.Handle(\"{method.RpcMethodName}\", async (global::System.Text.Json.JsonElement? __args, global::System.Threading.CancellationToken __ct) =>");
        sb.AppendLine($"{indent}        {{");
        EmitParameterDeserialization(sb, method, indent);
        EmitMethodInvocation(sb, method, indent);
        sb.AppendLine($"{indent}        }});");
    }

    private static void EmitStreamingHandler(StringBuilder sb, BridgeMethodModel method, string indent)
    {
        var innerType = method.AsyncEnumerableInnerType ?? "object";
        var hasCt = method.HasCancellationToken;

        if (hasCt)
        {
            sb.AppendLine($"{indent}        rpc.Handle(\"{method.RpcMethodName}\", async (global::System.Text.Json.JsonElement? __args, global::System.Threading.CancellationToken __ct) =>");
        }
        else
        {
            sb.AppendLine($"{indent}        rpc.Handle(\"{method.RpcMethodName}\", async (global::System.Text.Json.JsonElement? __args) =>");
        }
        sb.AppendLine($"{indent}        {{");

        EmitParameterDeserialization(sb, method, indent);

        // When the handler has a CancellationToken, the RPC dispatcher's CTS is disposed after the
        // init response returns. Create a linked CTS whose lifetime extends to enumerator disposal,
        // so that subsequent MoveNextAsync calls (e.g. Task.Delay with CT) don't hit ObjectDisposedException.
        if (hasCt)
        {
            sb.AppendLine($"{indent}            var __streamCts = __ct.CanBeCanceled");
            sb.AppendLine($"{indent}                ? global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource(__ct)");
            sb.AppendLine($"{indent}                : null;");
            sb.AppendLine($"{indent}            var __streamCt = __streamCts?.Token ?? __ct;");
        }

        var ctVarName = hasCt ? "__streamCt" : "default";
        var paramList = string.Join(", ", method.Parameters.Select(p =>
            p.IsCancellationToken ? "__streamCt" : $"__{p.CamelCaseName}"));

        sb.AppendLine($"{indent}            var __enumerable = impl.{method.Name}({paramList});");
        sb.AppendLine($"{indent}            var __enumerator = __enumerable.GetAsyncEnumerator({ctVarName});");
        sb.AppendLine($"{indent}            var __token = global::System.Guid.NewGuid().ToString(\"N\");");
        sb.AppendLine();
        sb.AppendLine($"{indent}            // Prefetch first item for reduced latency");
        sb.AppendLine($"{indent}            object?[]? __prefetch = null;");
        sb.AppendLine($"{indent}            if (await __enumerator.MoveNextAsync().ConfigureAwait(false))");
        sb.AppendLine($"{indent}            {{");
        sb.AppendLine($"{indent}                __prefetch = new object?[] {{ __enumerator.Current }};");
        sb.AppendLine($"{indent}            }}");
        sb.AppendLine($"{indent}            else");
        sb.AppendLine($"{indent}            {{");
        sb.AppendLine($"{indent}                await __enumerator.DisposeAsync().ConfigureAwait(false);");
        if (hasCt)
            sb.AppendLine($"{indent}                __streamCts?.Dispose();");
        sb.AppendLine($"{indent}                return (object?)new {{ token = __token, values = global::System.Array.Empty<object>(), finished = true }};");
        sb.AppendLine($"{indent}            }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}            rpc.RegisterEnumerator(__token,");
        sb.AppendLine($"{indent}                async () =>");
        sb.AppendLine($"{indent}                {{");
        sb.AppendLine($"{indent}                    if (await __enumerator.MoveNextAsync().ConfigureAwait(false))");
        sb.AppendLine($"{indent}                        return ((object?)__enumerator.Current, false);");
        sb.AppendLine($"{indent}                    return (null, true);");
        sb.AppendLine($"{indent}                }},");
        if (hasCt)
        {
            sb.AppendLine($"{indent}                async () => {{ await __enumerator.DisposeAsync().ConfigureAwait(false); __streamCts?.Dispose(); }});");
        }
        else
        {
            sb.AppendLine($"{indent}                async () => await __enumerator.DisposeAsync().ConfigureAwait(false));");
        }
        sb.AppendLine();
        sb.AppendLine($"{indent}            return (object?)new {{ token = __token, values = __prefetch }};");

        sb.AppendLine($"{indent}        }});");
    }

    private static void EmitEventHandlers(StringBuilder sb, string serviceName, BridgeEventModel evt, string indent)
    {
        var subscribeName = $"{serviceName}.$subscribe.{evt.CamelCaseName}";
        var unsubscribeName = $"{serviceName}.$unsubscribe.{evt.CamelCaseName}";
        var eventMethodName = $"{serviceName}.$event.{evt.CamelCaseName}";

        sb.AppendLine();
        sb.AppendLine($"{indent}        // Event: {evt.PropertyName}");
        sb.AppendLine($"{indent}        var __{evt.CamelCaseName}Subscribed = false;");
        sb.AppendLine($"{indent}        var __{evt.CamelCaseName}Event = impl.{evt.PropertyName} as global::Agibuild.Fulora.BridgeEvent<{evt.PayloadTypeFullName}>;");
        sb.AppendLine($"{indent}        if (__{evt.CamelCaseName}Event != null)");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            __{evt.CamelCaseName}Event.Connect(payload =>");
        sb.AppendLine($"{indent}            {{");
        sb.AppendLine($"{indent}                if (__{evt.CamelCaseName}Subscribed)");
        sb.AppendLine($"{indent}                    _ = rpc.NotifyAsync(\"{eventMethodName}\", payload);");
        sb.AppendLine($"{indent}            }});");
        sb.AppendLine($"{indent}        }}");

        sb.AppendLine($"{indent}        rpc.Handle(\"{subscribeName}\", (global::System.Text.Json.JsonElement? __args) =>");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            __{evt.CamelCaseName}Subscribed = true;");
        sb.AppendLine($"{indent}            return (object?)true;");
        sb.AppendLine($"{indent}        }});");

        sb.AppendLine($"{indent}        rpc.Handle(\"{unsubscribeName}\", (global::System.Text.Json.JsonElement? __args) =>");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            __{evt.CamelCaseName}Subscribed = false;");
        sb.AppendLine($"{indent}            return (object?)true;");
        sb.AppendLine($"{indent}        }});");
    }

    private static void EmitParameterDeserialization(StringBuilder sb, BridgeMethodModel method, string indent)
    {
        foreach (var param in method.Parameters)
        {
            if (param.IsCancellationToken)
                continue;

            var camel = param.CamelCaseName;
            var type = param.TypeFullName;

            if (param.IsNullable || param.HasDefaultValue)
            {
                var defaultVal = param.HasDefaultValue ? param.DefaultValueLiteral ?? "default" : "default";
                sb.AppendLine($"{indent}            {type} __{camel} = {defaultVal};");
                sb.AppendLine($"{indent}            if (__args.HasValue && __args.Value.TryGetProperty(\"{camel}\", out var __{camel}Prop) && __{camel}Prop.ValueKind != global::System.Text.Json.JsonValueKind.Null)");
                sb.AppendLine($"{indent}                __{camel} = __{camel}Prop.Deserialize<{type}>(BridgeGeneratedJsonOptions.Instance);");
            }
            else
            {
                sb.AppendLine($"{indent}            var __{camel}Prop = __args.HasValue && __args.Value.TryGetProperty(\"{camel}\", out var __p_{camel}) ? __p_{camel} : default;");
                sb.AppendLine($"{indent}            var __{camel} = __{camel}Prop.Deserialize<{type}>(BridgeGeneratedJsonOptions.Instance)!;");
            }
        }
    }

    private static void EmitMethodInvocation(StringBuilder sb, BridgeMethodModel method, string indent)
    {
        var paramList = string.Join(", ", method.Parameters.Select(p =>
            p.IsCancellationToken ? "__ct" : $"__{p.CamelCaseName}"));

        if (method.IsAsync && method.HasReturnValue)
        {
            sb.AppendLine($"{indent}            var __result = await impl.{method.Name}({paramList}).ConfigureAwait(false);");
            sb.AppendLine($"{indent}            return (object?)__result;");
        }
        else if (method.IsAsync)
        {
            sb.AppendLine($"{indent}            await impl.{method.Name}({paramList}).ConfigureAwait(false);");
            sb.AppendLine($"{indent}            return (object?)null;");
        }
        else if (method.HasReturnValue)
        {
            sb.AppendLine($"{indent}            var __result = impl.{method.Name}({paramList});");
            sb.AppendLine($"{indent}            return (object?)__result;");
        }
        else
        {
            sb.AppendLine($"{indent}            impl.{method.Name}({paramList});");
            sb.AppendLine($"{indent}            return (object?)null;");
        }
    }

    private static void EmitUnregisterHandlers(StringBuilder sb, BridgeInterfaceModel model, string indent)
    {
        sb.AppendLine($"{indent}    public void UnregisterHandlers(global::Agibuild.Fulora.IWebViewRpcService rpc)");
        sb.AppendLine($"{indent}    {{");

        foreach (var method in model.Methods)
        {
            sb.AppendLine($"{indent}        rpc.UnregisterHandler(\"{method.RpcMethodName}\");");
        }

        foreach (var evt in model.Events)
        {
            sb.AppendLine($"{indent}        rpc.UnregisterHandler(\"{model.ServiceName}.$subscribe.{evt.CamelCaseName}\");");
            sb.AppendLine($"{indent}        rpc.UnregisterHandler(\"{model.ServiceName}.$unsubscribe.{evt.CamelCaseName}\");");
        }

        sb.AppendLine($"{indent}    }}");
    }

    private static void EmitDisconnectEvents(StringBuilder sb, BridgeInterfaceModel model, string indent)
    {
        sb.AppendLine($"{indent}    public void DisconnectEvents({model.InterfaceFullName} impl)");
        sb.AppendLine($"{indent}    {{");

        foreach (var evt in model.Events)
        {
            sb.AppendLine($"{indent}        (impl.{evt.PropertyName} as global::Agibuild.Fulora.BridgeEvent<{evt.PayloadTypeFullName}>)?.Disconnect();");
        }

        sb.AppendLine($"{indent}    }}");
    }

    private static void EmitGetJsStub(StringBuilder sb, BridgeInterfaceModel model, string indent)
    {
        sb.AppendLine($"{indent}    public string GetJsStub() => @\"");
        sb.AppendLine($"{indent}(function() {{");
        sb.AppendLine($"{indent}    if (!window.agWebView) window.agWebView = {{}};");
        sb.AppendLine($"{indent}    if (!window.agWebView.bridge) window.agWebView.bridge = {{}};");
        sb.Append($"{indent}    window.agWebView.bridge.{model.ServiceName} = {{ ");

        var jsMethodParts = new List<string>();
        var overloadGroups = model.Methods
            .GroupBy(m => m.CamelCaseName)
            .ToDictionary(g => g.Key, g => g.ToList());

        foreach (var kv in overloadGroups)
        {
            if (kv.Value.Count == 1)
            {
                jsMethodParts.Add(EmitSingleJsMethod(kv.Value[0]));
            }
            else
            {
                jsMethodParts.Add(EmitOverloadedJsMethod(kv.Key, kv.Value));
            }
        }
        sb.Append(string.Join(", ", jsMethodParts));

        // Event properties
        foreach (var evt in model.Events)
        {
            sb.Append($", {evt.CamelCaseName}: (function() {{ ");
            sb.Append("var hs = []; ");
            sb.Append($"window.agWebView.rpc.handle('{model.ServiceName}.$event.{evt.CamelCaseName}', function(p) {{ ");
            sb.Append("for (var i = 0; i < hs.length; i++) hs[i](p); ");
            sb.Append("}); ");
            sb.Append("return { on: function(h) { hs.push(h); ");
            sb.Append($"if (hs.length === 1) window.agWebView.rpc.invoke('{model.ServiceName}.$subscribe.{evt.CamelCaseName}'); ");
            sb.Append("return function() { hs = hs.filter(function(x) { return x !== h; }); ");
            sb.Append($"if (hs.length === 0) window.agWebView.rpc.invoke('{model.ServiceName}.$unsubscribe.{evt.CamelCaseName}'); ");
            sb.Append("}; }, ");
            sb.Append("off: function(h) { hs = hs.filter(function(x) { return x !== h; }); ");
            sb.Append($"if (hs.length === 0) window.agWebView.rpc.invoke('{model.ServiceName}.$unsubscribe.{evt.CamelCaseName}'); ");
            sb.Append("} }; })()");
        }

        sb.AppendLine(" };");
        sb.AppendLine($"{indent}}})();\";");
    }

    private static string EmitSingleJsMethod(BridgeMethodModel m)
    {
        if (m.IsAsyncEnumerable)
        {
            var rpcParamNames = m.Parameters
                .Where(p => !p.IsCancellationToken)
                .Select(p => p.CamelCaseName)
                .ToList();

            var jb = new StringBuilder();
            jb.Append($"{m.CamelCaseName}: function(");
            jb.Append(string.Join(", ", rpcParamNames));
            jb.Append(") { ");

            var paramsObj = rpcParamNames.Count > 0
                ? "{ " + string.Join(", ", rpcParamNames.Select(n => $"{n}: {n}")) + " }"
                : "undefined";

            jb.Append($"return window.agWebView.rpc._createAsyncIterable('{m.RpcMethodName}', {paramsObj}); }}");
            return jb.ToString();
        }

        if (m.HasCancellationToken)
        {
            var rpcParamNames = m.Parameters
                .Where(p => !p.IsCancellationToken)
                .Select(p => p.CamelCaseName)
                .ToList();

            var jb = new StringBuilder();
            jb.Append($"{m.CamelCaseName}: function(");
            jb.Append(string.Join(", ", rpcParamNames.Concat(OptionsParam)));
            jb.Append(") { ");

            var paramsObj = rpcParamNames.Count > 0
                ? "{ " + string.Join(", ", rpcParamNames.Select(n => $"{n}: {n}")) + " }"
                : "undefined";

            jb.Append($"var __call = window.agWebView.rpc.invoke('{m.RpcMethodName}', {paramsObj}");
            jb.Append(", options && options.signal");
            jb.Append(");");
            if (IsByteArrayType(m.InnerReturnTypeFullName ?? m.ReturnTypeFullName))
            {
                jb.Append(" return __call.then(function(__r) { return window.agWebView.rpc._decodeBinaryResult(__r); }); }");
            }
            else
            {
                jb.Append(" return __call; }");
            }
            return jb.ToString();
        }

        if (IsByteArrayType(m.InnerReturnTypeFullName ?? m.ReturnTypeFullName))
        {
            return $"{m.CamelCaseName}: function(params) {{ var __call = window.agWebView.rpc.invoke('{m.RpcMethodName}', params); return __call.then(function(__r) {{ return window.agWebView.rpc._decodeBinaryResult(__r); }}); }}";
        }

        return $"{m.CamelCaseName}: function(params) {{ return window.agWebView.rpc.invoke('{m.RpcMethodName}', params); }}";
    }

    private static string EmitOverloadedJsMethod(string camelName, List<BridgeMethodModel> overloads)
    {
        var sorted = overloads.OrderByDescending(m => m.VisibleParameterCount).ToList();
        var allParamNames = sorted[0].Parameters
            .Where(p => !p.IsCancellationToken)
            .Select(p => p.CamelCaseName)
            .ToList();

        var jb = new StringBuilder();
        jb.Append($"{camelName}: function() {{ ");

        for (int i = 0; i < sorted.Count; i++)
        {
            var m = sorted[i];
            var visibleParams = m.Parameters.Where(p => !p.IsCancellationToken).ToList();
            var paramsObj = visibleParams.Count > 0
                ? "{ " + string.Join(", ", visibleParams.Select((p, idx) => $"{p.CamelCaseName}: arguments[{idx}]")) + " }"
                : "undefined";

            if (i < sorted.Count - 1)
            {
                jb.Append($"if (arguments.length >= {visibleParams.Count}) ");
                if (IsByteArrayType(m.InnerReturnTypeFullName ?? m.ReturnTypeFullName))
                {
                    jb.Append($"return window.agWebView.rpc.invoke('{m.RpcMethodName}', {paramsObj}).then(function(__r) {{ return window.agWebView.rpc._decodeBinaryResult(__r); }}); ");
                }
                else
                {
                    jb.Append($"return window.agWebView.rpc.invoke('{m.RpcMethodName}', {paramsObj}); ");
                }
            }
            else
            {
                if (IsByteArrayType(m.InnerReturnTypeFullName ?? m.ReturnTypeFullName))
                {
                    jb.Append($"return window.agWebView.rpc.invoke('{m.RpcMethodName}', {paramsObj}).then(function(__r) {{ return window.agWebView.rpc._decodeBinaryResult(__r); }}); ");
                }
                else
                {
                    jb.Append($"return window.agWebView.rpc.invoke('{m.RpcMethodName}', {paramsObj}); ");
                }
            }
        }

        jb.Append('}');
        return jb.ToString();
    }

    private static string GetFullClassName(string ns, string className)
    {
        return string.IsNullOrEmpty(ns) ? $"global::{className}" : $"global::{ns}.{className}";
    }

    private static bool IsByteArrayType(string? type)
    {
        if (string.IsNullOrWhiteSpace(type))
            return false;

        var normalized = type!.Trim();
        if (normalized.EndsWith("?", System.StringComparison.Ordinal))
            normalized = normalized.Substring(0, normalized.Length - 1);

        return normalized is "byte[]" or "System.Byte[]";
    }
}
