using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Agibuild.Fulora.Bridge.Generator;

/// <summary>
/// Emits TypeScript declaration files (.d.ts) as string constants embedded in a generated C# class.
/// The MSBuild target or runtime can extract these constants and write them to disk.
/// </summary>
internal static class TypeScriptEmitter
{
    public static string EmitDeclarations(BridgeContractModel ir)
    {
        var exports = ir.Services.Where(s => s.Direction == BridgeDirection.Export).ToList();
        var imports = ir.Services.Where(s => s.Direction == BridgeDirection.Import).ToList();
        return EmitDeclarationsInternal(exports, imports, ir.Dtos);
    }

    public static string EmitDeclarations(IReadOnlyList<BridgeInterfaceModel> exports, IReadOnlyList<BridgeInterfaceModel> imports)
    {
        return EmitDeclarationsInternal(exports, imports, System.Collections.Immutable.ImmutableArray<BridgeDtoModel>.Empty);
    }

    private static string EmitDeclarationsInternal(
        IReadOnlyList<BridgeInterfaceModel> exports,
        IReadOnlyList<BridgeInterfaceModel> imports,
        System.Collections.Immutable.ImmutableArray<BridgeDtoModel> dtos)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Collect namespace from first model
        var ns = exports.Count > 0 ? exports[0].Namespace
               : imports.Count > 0 ? imports[0].Namespace
               : "";

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        var indent = string.IsNullOrEmpty(ns) ? "" : "    ";

        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}/// Contains auto-generated TypeScript declarations for bridge interfaces.");
        sb.AppendLine($"{indent}/// Use <c>BridgeTypeScriptDeclarations.All</c> to get the full .d.ts content.");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}[global::System.CodeDom.Compiler.GeneratedCode(\"Agibuild.WebView.BridgeGenerator\", \"1.0.0\")]");
        sb.AppendLine($"{indent}internal static class BridgeTypeScriptDeclarations");
        sb.AppendLine($"{indent}{{");

        // Per-service declarations
        foreach (var model in exports)
        {
            var tsContent = GenerateTsInterface(model, isExport: true);
            sb.AppendLine($"{indent}    /// <summary>TypeScript declaration for {model.InterfaceName}.</summary>");
            sb.AppendLine($"{indent}    public const string {model.ServiceName} = @\"{EscapeVerbatim(tsContent)}\";");
            sb.AppendLine();
        }

        foreach (var model in imports)
        {
            var tsContent = GenerateTsInterface(model, isExport: false);
            sb.AppendLine($"{indent}    /// <summary>TypeScript declaration for {model.InterfaceName}.</summary>");
            sb.AppendLine($"{indent}    public const string {model.ServiceName} = @\"{EscapeVerbatim(tsContent)}\";");
            sb.AppendLine();
        }

        // Combined "All" declaration
        var allTs = new StringBuilder();
        allTs.AppendLine("// Auto-generated by Agibuild.Fulora.Bridge.Generator");
        allTs.AppendLine("// Do not edit manually.");
        allTs.AppendLine();

        if (dtos.Length > 0)
        {
            foreach (var dto in dtos)
                allTs.AppendLine(GenerateDtoDeclaration(dto));
        }

        foreach (var model in exports)
            allTs.AppendLine(GenerateTsInterface(model, isExport: true));
        foreach (var model in imports)
            allTs.AppendLine(GenerateTsInterface(model, isExport: false));

        // BridgeEvent<T> utility type
        var hasEvents = exports.Any(m => m.Events.Length > 0);
        if (hasEvents)
        {
            allTs.AppendLine("export interface BridgeEvent<T> {");
            allTs.AppendLine("  on(handler: (payload: T) => void): () => void;");
            allTs.AppendLine("  off(handler: (payload: T) => void): void;");
            allTs.AppendLine("}");
            allTs.AppendLine();
        }

        // Bridge global declaration
        allTs.AppendLine("declare global {");
        allTs.AppendLine("  interface Window {");
        allTs.AppendLine("    agWebView: {");
        allTs.AppendLine("      bridge: {");
        foreach (var model in exports)
        {
            allTs.AppendLine($"        {ModelExtractor.ToCamelCase(model.ServiceName)}: {model.ServiceName};");
        }
        allTs.AppendLine("      };");
        allTs.AppendLine("      rpc: {");
        allTs.AppendLine("        invoke(method: string, params?: unknown, signal?: AbortSignal): Promise<unknown>;");
        allTs.AppendLine("        handle(method: string, handler: (params: unknown) => unknown | Promise<unknown>): void;");
        allTs.AppendLine("        batch(calls: Array<{ method: string; params?: unknown }>): Promise<unknown[]>;");
        allTs.AppendLine("        _createAsyncIterable(method: string, params?: unknown): AsyncIterable<unknown>;");
        allTs.AppendLine("        _decodeBinaryResult?(result: unknown): unknown;");
        allTs.AppendLine("      };");
        allTs.AppendLine("    };");
        allTs.AppendLine("  }");
        allTs.AppendLine("}");

        sb.AppendLine($"{indent}    /// <summary>Complete .d.ts file content for all bridge interfaces.</summary>");
        sb.AppendLine($"{indent}    public const string All = @\"{EscapeVerbatim(allTs.ToString())}\";");
        sb.AppendLine();

        var ir = new BridgeContractModel
        {
            Services = System.Collections.Immutable.ImmutableArray.CreateRange(
                exports.Concat(imports).Select(s => s)),
            Dtos = dtos,
        };

        var clientTs = TypeScriptClientEmitter.EmitClient(ir);
        sb.AppendLine($"{indent}    /// <summary>Typed client proxy module content for bridge.client.ts.</summary>");
        sb.AppendLine($"{indent}    public const string Client = @\"{EscapeVerbatim(clientTs)}\";");
        sb.AppendLine();

        var mockTs = TypeScriptMockEmitter.EmitMock(ir);
        sb.AppendLine($"{indent}    /// <summary>Mock stub module content for bridge.mock.ts.</summary>");
        sb.AppendLine($"{indent}    public const string Mock = @\"{EscapeVerbatim(mockTs)}\";");

        sb.AppendLine($"{indent}}}");

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string GenerateTsInterface(BridgeInterfaceModel model, bool isExport)
    {
        var sb = new StringBuilder();
        var keyword = isExport ? "export" : "export";

        sb.AppendLine($"/** {(isExport ? "C# service exposed to JS" : "JS service callable from C#")} */");
        sb.AppendLine($"{keyword} interface {model.ServiceName} {{");

        foreach (var method in model.Methods)
        {
            sb.AppendLine($"  {EmitTsMethodSignature(method)}");
        }

        foreach (var evt in model.Events)
        {
            var tsPayload = TypeRefToTypeScript(evt.PayloadTypeRef);
            sb.AppendLine($"  {evt.CamelCaseName}: BridgeEvent<{tsPayload}>;");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string EmitTsMethodSignature(BridgeMethodModel method)
    {
        var regularParams = method.Parameters.Where(p => !p.IsCancellationToken).ToList();
        var hasCancellation = method.HasCancellationToken;

        var tsParamParts = regularParams.Select(p =>
        {
            var tsType = TypeRefToTypeScript(p.TypeRef);
            var optional = p.IsNullable || p.HasDefaultValue ? "?" : "";
            return $"{p.CamelCaseName}{optional}: {tsType}";
        }).ToList();

        if (hasCancellation)
        {
            tsParamParts.Add("options?: { signal?: AbortSignal }");
        }

        var tsParams = string.Join(", ", tsParamParts);

        string tsReturn;
        if (method.IsAsyncEnumerable)
        {
            var innerType = method.AsyncEnumerableInnerTypeRef is null
                ? "unknown"
                : TypeRefToTypeScript(method.AsyncEnumerableInnerTypeRef);
            tsReturn = $"AsyncIterable<{innerType}>";
        }
        else
        {
            tsReturn = method.HasReturnValue
                ? $"Promise<{(method.InnerReturnTypeRef is null ? "void" : TypeRefToTypeScript(method.InnerReturnTypeRef))}>"
                : "Promise<void>";
        }

        return $"{method.CamelCaseName}({tsParams}): {tsReturn};";
    }

    internal static string CSharpTypeToTypeScript(string csharpType)
    {
        // Strip nullable annotation
        var type = csharpType.TrimEnd('?');

        // Primitives
        if (type is "string" or "System.String") return "string";
        if (type is "int" or "System.Int32" or "long" or "System.Int64"
            or "short" or "System.Int16" or "float" or "System.Single"
            or "double" or "System.Double" or "decimal" or "System.Decimal"
            or "byte" or "System.Byte") return "number";
        if (type is "bool" or "System.Boolean") return "boolean";
        if (type is "void" or "System.Void") return "void";
        if (type is "System.DateTime" or "System.DateTimeOffset") return "string"; // ISO 8601
        if (type is "System.Guid") return "string";
        if (type is "byte[]" or "System.Byte[]") return "Uint8Array";

        // IBridgeEvent
        if (type.StartsWith("Agibuild.Fulora.IBridgeEvent<"))
        {
            var inner = ExtractGenericArg(type);
            return $"BridgeEvent<{CSharpTypeToTypeScript(inner)}>";
        }

        // IAsyncEnumerable
        if (type.StartsWith("System.Collections.Generic.IAsyncEnumerable<"))
        {
            var inner = ExtractGenericArg(type);
            return $"AsyncIterable<{CSharpTypeToTypeScript(inner)}>";
        }

        // Collections
        if (type.StartsWith("System.Collections.Generic.List<") || type.StartsWith("System.Collections.Generic.IList<")
            || type.StartsWith("System.Collections.Generic.IReadOnlyList<") || type.StartsWith("System.Collections.Generic.IEnumerable<"))
        {
            var inner = ExtractGenericArg(type);
            return $"{CSharpTypeToTypeScript(inner)}[]";
        }

        if (type.StartsWith("System.Collections.Generic.Dictionary<") || type.StartsWith("System.Collections.Generic.IDictionary<"))
        {
            var args = ExtractGenericArgs(type);
            if (args.Count >= 2)
                return $"Record<{CSharpTypeToTypeScript(args[0])}, {CSharpTypeToTypeScript(args[1])}>";
        }

        // Fallback: use the short type name
        var lastDot = type.LastIndexOf('.');
        return lastDot >= 0 ? type.Substring(lastDot + 1) : type;
    }

    private static string ExtractGenericArg(string type)
    {
        var start = type.IndexOf('<');
        var end = type.LastIndexOf('>');
        if (start >= 0 && end > start)
            return type.Substring(start + 1, end - start - 1).Trim();
        return "unknown";
    }

    private static List<string> ExtractGenericArgs(string type)
    {
        var inner = ExtractGenericArg(type);
        var args = new List<string>();
        int depth = 0;
        int start = 0;

        for (int i = 0; i < inner.Length; i++)
        {
            switch (inner[i])
            {
                case '<':
                    depth++;
                    break;
                case '>':
                    depth--;
                    break;
                case ',' when depth == 0:
                    args.Add(inner.Substring(start, i - start).Trim());
                    start = i + 1;
                    break;
            }
        }

        args.Add(inner.Substring(start).Trim());
        return args;
    }

    private static string EscapeVerbatim(string s) => s.Replace("\"", "\"\"");

    // ==================== DTO generation ====================

    private static string GenerateDtoDeclaration(BridgeDtoModel dto)
    {
        var sb = new StringBuilder();

        if (dto.IsEnum)
        {
            sb.AppendLine($"export enum {dto.Name} {{");
            for (int i = 0; i < dto.EnumMembers.Length; i++)
            {
                var member = dto.EnumMembers[i];
                var comma = i < dto.EnumMembers.Length - 1 ? "," : "";
                sb.AppendLine($"  {member.Name} = {member.ValueLiteral}{comma}");
            }
            sb.AppendLine("}");
        }
        else
        {
            sb.AppendLine($"export interface {dto.Name} {{");
            foreach (var prop in dto.Properties)
            {
                var optional = prop.IsNullable ? "?" : "";
                var tsType = TypeRefToTypeScript(prop.TypeRef);
                sb.AppendLine($"  {prop.CamelCaseName}{optional}: {tsType};");
            }
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    internal static string TypeRefToTypeScript(BridgeTypeRef typeRef)
    {
        switch (typeRef.Kind)
        {
            case BridgeTypeKind.String:
            case BridgeTypeKind.DateTime:
            case BridgeTypeKind.Guid:
                return "string";
            case BridgeTypeKind.Number:
                return "number";
            case BridgeTypeKind.Boolean:
                return "boolean";
            case BridgeTypeKind.Void:
                return "void";
            case BridgeTypeKind.Binary:
                return "Uint8Array";
            case BridgeTypeKind.Array:
                if (typeRef.ElementType != null)
                    return $"{TypeRefToTypeScript(typeRef.ElementType)}[]";
                return "unknown[]";
            case BridgeTypeKind.Dictionary:
                if (typeRef.TypeArguments.Length >= 2)
                    return $"Record<{TypeRefToTypeScript(typeRef.TypeArguments[0])}, {TypeRefToTypeScript(typeRef.TypeArguments[1])}>";
                return "Record<string, unknown>";
            case BridgeTypeKind.Dto:
            case BridgeTypeKind.Enum:
                return typeRef.Name;
            case BridgeTypeKind.BridgeEvent:
                if (typeRef.TypeArguments.Length > 0)
                    return $"BridgeEvent<{TypeRefToTypeScript(typeRef.TypeArguments[0])}>";
                return "BridgeEvent<unknown>";
            case BridgeTypeKind.AsyncEnumerable:
                if (typeRef.ElementType != null)
                    return $"AsyncIterable<{TypeRefToTypeScript(typeRef.ElementType)}>";
                return "AsyncIterable<unknown>";
            default:
                return "unknown";
        }
    }
}
