using System;
using System.Linq;
using System.Text;

namespace Agibuild.Fulora.Bridge.Generator;

/// <summary>
/// Emits a deterministic browser mock module (bridge.mock.ts) from the Bridge Contract IR.
/// Allows SPA development outside the native host by providing stub service implementations.
/// </summary>
internal static class TypeScriptMockEmitter
{
    public static string EmitMock(BridgeContractModel ir)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by Agibuild.Fulora.Bridge.Generator");
        sb.AppendLine("// Do not edit manually.");
        sb.AppendLine("//");
        sb.AppendLine("// Mock stubs for standalone browser development.");
        sb.AppendLine("// Import and call installBridgeMock() before your app initializes.");
        sb.AppendLine();

        var exports = ir.Services
            .Where(s => s.Direction == BridgeDirection.Export)
            .ToList();

        if (exports.Count == 0)
            return sb.ToString();

        sb.AppendLine("type RpcHandler = (params: unknown) => unknown | Promise<unknown>;");
        sb.AppendLine();

        sb.AppendLine("export function installBridgeMock() {");
        sb.AppendLine("  const handlers: Record<string, RpcHandler> = {};");
        sb.AppendLine();
        sb.AppendLine("  const rpc = {");
        sb.AppendLine("    invoke(method: string, params?: unknown): Promise<unknown> {");
        sb.AppendLine("      const handler = handlers[method];");
        sb.AppendLine("      if (!handler) return Promise.reject(new Error(`Mock: no handler for ${method}`));");
        sb.AppendLine("      return Promise.resolve(handler(params));");
        sb.AppendLine("    },");
        sb.AppendLine("    handle(method: string, handler: RpcHandler) { handlers[method] = handler; },");
        sb.AppendLine("    batch(calls: Array<{ method: string; params?: unknown }>): Promise<unknown[]> {");
        sb.AppendLine("      return Promise.all(calls.map(c => rpc.invoke(c.method, c.params)));");
        sb.AppendLine("    },");
        sb.AppendLine("    _createAsyncIterable(_method: string, _params?: unknown) {");
        sb.AppendLine("      return { async *[Symbol.asyncIterator]() { /* empty */ } };");
        sb.AppendLine("    },");
        sb.AppendLine("    _decodeBinaryResult(r: unknown) { return r; },");
        sb.AppendLine("  };");
        sb.AppendLine();

        sb.AppendLine("  const bridge: Record<string, Record<string, (...args: unknown[]) => Promise<unknown>>> = {};");
        sb.AppendLine();

        foreach (var service in exports)
        {
            EmitServiceMock(sb, service);
        }

        sb.AppendLine("  (window as any).agWebView = { rpc, bridge };");
        sb.AppendLine();
        sb.AppendLine("  return { rpc, bridge, handlers };");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitServiceMock(StringBuilder sb, BridgeInterfaceModel service)
    {
        var varName = ModelExtractor.ToCamelCase(service.ServiceName);
        sb.AppendLine($"  bridge['{varName}'] = {{");

        foreach (var method in service.Methods)
        {
            var defaultReturn = GetDefaultReturnValue(method);
            sb.AppendLine($"    {method.CamelCaseName}: (..._args: unknown[]) => Promise.resolve({defaultReturn}),");
        }

        sb.AppendLine("  };");
        sb.AppendLine();
    }

    private static string GetDefaultReturnValue(BridgeMethodModel method)
    {
        if (!method.HasReturnValue)
            return "undefined";

        var tsType = method.InnerReturnTypeRef is null
            ? "void"
            : TypeScriptEmitter.TypeRefToTypeScript(method.InnerReturnTypeRef);

        if (tsType == "string") return "''";
        if (tsType == "number") return "0";
        if (tsType == "boolean") return "false";
        if (tsType == "void") return "undefined";
        if (tsType.EndsWith("[]", StringComparison.Ordinal)) return "[]";
        if (tsType == "Uint8Array") return "new Uint8Array()";
        if (tsType.StartsWith("Record<", StringComparison.Ordinal)) return "{}";

        return "{} as any";
    }
}
