### YamlMime:ManagedReference
items:
- uid: Agibuild.Fulora.IWebViewEnvironmentOptions
  commentId: T:Agibuild.Fulora.IWebViewEnvironmentOptions
  id: IWebViewEnvironmentOptions
  parent: Agibuild.Fulora
  children:
  - Agibuild.Fulora.IWebViewEnvironmentOptions.CustomSchemes
  - Agibuild.Fulora.IWebViewEnvironmentOptions.CustomUserAgent
  - Agibuild.Fulora.IWebViewEnvironmentOptions.EnableDevTools
  - Agibuild.Fulora.IWebViewEnvironmentOptions.PreloadScripts
  - Agibuild.Fulora.IWebViewEnvironmentOptions.TransparentBackground
  - Agibuild.Fulora.IWebViewEnvironmentOptions.UseEphemeralSession
  langs:
  - csharp
  - vb
  name: IWebViewEnvironmentOptions
  nameWithType: IWebViewEnvironmentOptions
  fullName: Agibuild.Fulora.IWebViewEnvironmentOptions
  type: Interface
  source:
    remote:
      path: src/Agibuild.Fulora.Core/WebViewInterfaces.cs
      branch: main
      repo: https://github.com/AGIBuild/Agibuild.Fulora.git
    id: IWebViewEnvironmentOptions
    path: ../src/Agibuild.Fulora.Core/WebViewInterfaces.cs
    startLine: 115
  assemblies:
  - Agibuild.Fulora.Core
  namespace: Agibuild.Fulora
  syntax:
    content: public interface IWebViewEnvironmentOptions
    content.vb: Public Interface IWebViewEnvironmentOptions
- uid: Agibuild.Fulora.IWebViewEnvironmentOptions.EnableDevTools
  commentId: P:Agibuild.Fulora.IWebViewEnvironmentOptions.EnableDevTools
  id: EnableDevTools
  parent: Agibuild.Fulora.IWebViewEnvironmentOptions
  langs:
  - csharp
  - vb
  name: EnableDevTools
  nameWithType: IWebViewEnvironmentOptions.EnableDevTools
  fullName: Agibuild.Fulora.IWebViewEnvironmentOptions.EnableDevTools
  type: Property
  source:
    remote:
      path: src/Agibuild.Fulora.Core/WebViewInterfaces.cs
      branch: main
      repo: https://github.com/AGIBuild/Agibuild.Fulora.git
    id: EnableDevTools
    path: ../src/Agibuild.Fulora.Core/WebViewInterfaces.cs
    startLine: 117
  assemblies:
  - Agibuild.Fulora.Core
  namespace: Agibuild.Fulora
  syntax:
    content: bool EnableDevTools { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Property EnableDevTools As Boolean
  overload: Agibuild.Fulora.IWebViewEnvironmentOptions.EnableDevTools*
- uid: Agibuild.Fulora.IWebViewEnvironmentOptions.CustomUserAgent
  commentId: P:Agibuild.Fulora.IWebViewEnvironmentOptions.CustomUserAgent
  id: CustomUserAgent
  parent: Agibuild.Fulora.IWebViewEnvironmentOptions
  langs:
  - csharp
  - vb
  name: CustomUserAgent
  nameWithType: IWebViewEnvironmentOptions.CustomUserAgent
  fullName: Agibuild.Fulora.IWebViewEnvironmentOptions.CustomUserAgent
  type: Property
  source:
    remote:
      path: src/Agibuild.Fulora.Core/WebViewInterfaces.cs
      branch: main
      repo: https://github.com/AGIBuild/Agibuild.Fulora.git
    id: CustomUserAgent
    path: ../src/Agibuild.Fulora.Core/WebViewInterfaces.cs
    startLine: 118
  assemblies:
  - Agibuild.Fulora.Core
  namespace: Agibuild.Fulora
  syntax:
    content: string? CustomUserAgent { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property CustomUserAgent As String
  overload: Agibuild.Fulora.IWebViewEnvironmentOptions.CustomUserAgent*
- uid: Agibuild.Fulora.IWebViewEnvironmentOptions.UseEphemeralSession
  commentId: P:Agibuild.Fulora.IWebViewEnvironmentOptions.UseEphemeralSession
  id: UseEphemeralSession
  parent: Agibuild.Fulora.IWebViewEnvironmentOptions
  langs:
  - csharp
  - vb
  name: UseEphemeralSession
  nameWithType: IWebViewEnvironmentOptions.UseEphemeralSession
  fullName: Agibuild.Fulora.IWebViewEnvironmentOptions.UseEphemeralSession
  type: Property
  source:
    remote:
      path: src/Agibuild.Fulora.Core/WebViewInterfaces.cs
      branch: main
      repo: https://github.com/AGIBuild/Agibuild.Fulora.git
    id: UseEphemeralSession
    path: ../src/Agibuild.Fulora.Core/WebViewInterfaces.cs
    startLine: 119
  assemblies:
  - Agibuild.Fulora.Core
  namespace: Agibuild.Fulora
  syntax:
    content: bool UseEphemeralSession { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Property UseEphemeralSession As Boolean
  overload: Agibuild.Fulora.IWebViewEnvironmentOptions.UseEphemeralSession*
- uid: Agibuild.Fulora.IWebViewEnvironmentOptions.TransparentBackground
  commentId: P:Agibuild.Fulora.IWebViewEnvironmentOptions.TransparentBackground
  id: TransparentBackground
  parent: Agibuild.Fulora.IWebViewEnvironmentOptions
  langs:
  - csharp
  - vb
  name: TransparentBackground
  nameWithType: IWebViewEnvironmentOptions.TransparentBackground
  fullName: Agibuild.Fulora.IWebViewEnvironmentOptions.TransparentBackground
  type: Property
  source:
    remote:
      path: src/Agibuild.Fulora.Core/WebViewInterfaces.cs
      branch: main
      repo: https://github.com/AGIBuild/Agibuild.Fulora.git
    id: TransparentBackground
    path: ../src/Agibuild.Fulora.Core/WebViewInterfaces.cs
    startLine: 120
  assemblies:
  - Agibuild.Fulora.Core
  namespace: Agibuild.Fulora
  syntax:
    content: bool TransparentBackground { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Property TransparentBackground As Boolean
  overload: Agibuild.Fulora.IWebViewEnvironmentOptions.TransparentBackground*
- uid: Agibuild.Fulora.IWebViewEnvironmentOptions.CustomSchemes
  commentId: P:Agibuild.Fulora.IWebViewEnvironmentOptions.CustomSchemes
  id: CustomSchemes
  parent: Agibuild.Fulora.IWebViewEnvironmentOptions
  langs:
  - csharp
  - vb
  name: CustomSchemes
  nameWithType: IWebViewEnvironmentOptions.CustomSchemes
  fullName: Agibuild.Fulora.IWebViewEnvironmentOptions.CustomSchemes
  type: Property
  source:
    remote:
      path: src/Agibuild.Fulora.Core/WebViewInterfaces.cs
      branch: main
      repo: https://github.com/AGIBuild/Agibuild.Fulora.git
    id: CustomSchemes
    path: ../src/Agibuild.Fulora.Core/WebViewInterfaces.cs
    startLine: 121
  assemblies:
  - Agibuild.Fulora.Core
  namespace: Agibuild.Fulora
  syntax:
    content: IReadOnlyList<CustomSchemeRegistration> CustomSchemes { get; }
    parameters: []
    return:
      type: System.Collections.Generic.IReadOnlyList{Agibuild.Fulora.CustomSchemeRegistration}
    content.vb: ReadOnly Property CustomSchemes As IReadOnlyList(Of CustomSchemeRegistration)
  overload: Agibuild.Fulora.IWebViewEnvironmentOptions.CustomSchemes*
- uid: Agibuild.Fulora.IWebViewEnvironmentOptions.PreloadScripts
  commentId: P:Agibuild.Fulora.IWebViewEnvironmentOptions.PreloadScripts
  id: PreloadScripts
  parent: Agibuild.Fulora.IWebViewEnvironmentOptions
  langs:
  - csharp
  - vb
  name: PreloadScripts
  nameWithType: IWebViewEnvironmentOptions.PreloadScripts
  fullName: Agibuild.Fulora.IWebViewEnvironmentOptions.PreloadScripts
  type: Property
  source:
    remote:
      path: src/Agibuild.Fulora.Core/WebViewInterfaces.cs
      branch: main
      repo: https://github.com/AGIBuild/Agibuild.Fulora.git
    id: PreloadScripts
    path: ../src/Agibuild.Fulora.Core/WebViewInterfaces.cs
    startLine: 122
  assemblies:
  - Agibuild.Fulora.Core
  namespace: Agibuild.Fulora
  syntax:
    content: IReadOnlyList<string> PreloadScripts { get; }
    parameters: []
    return:
      type: System.Collections.Generic.IReadOnlyList{System.String}
    content.vb: ReadOnly Property PreloadScripts As IReadOnlyList(Of String)
  overload: Agibuild.Fulora.IWebViewEnvironmentOptions.PreloadScripts*
references:
- uid: Agibuild.Fulora
  commentId: N:Agibuild.Fulora
  href: Agibuild.html
  name: Agibuild.Fulora
  nameWithType: Agibuild.Fulora
  fullName: Agibuild.Fulora
  spec.csharp:
  - uid: Agibuild
    name: Agibuild
    href: Agibuild.html
  - name: .
  - uid: Agibuild.Fulora
    name: Fulora
    href: Agibuild.Fulora.html
  spec.vb:
  - uid: Agibuild
    name: Agibuild
    href: Agibuild.html
  - name: .
  - uid: Agibuild.Fulora
    name: Fulora
    href: Agibuild.Fulora.html
- uid: Agibuild.Fulora.IWebViewEnvironmentOptions.EnableDevTools*
  commentId: Overload:Agibuild.Fulora.IWebViewEnvironmentOptions.EnableDevTools
  href: Agibuild.Fulora.IWebViewEnvironmentOptions.html#Agibuild_Fulora_IWebViewEnvironmentOptions_EnableDevTools
  name: EnableDevTools
  nameWithType: IWebViewEnvironmentOptions.EnableDevTools
  fullName: Agibuild.Fulora.IWebViewEnvironmentOptions.EnableDevTools
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Agibuild.Fulora.IWebViewEnvironmentOptions.CustomUserAgent*
  commentId: Overload:Agibuild.Fulora.IWebViewEnvironmentOptions.CustomUserAgent
  href: Agibuild.Fulora.IWebViewEnvironmentOptions.html#Agibuild_Fulora_IWebViewEnvironmentOptions_CustomUserAgent
  name: CustomUserAgent
  nameWithType: IWebViewEnvironmentOptions.CustomUserAgent
  fullName: Agibuild.Fulora.IWebViewEnvironmentOptions.CustomUserAgent
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Agibuild.Fulora.IWebViewEnvironmentOptions.UseEphemeralSession*
  commentId: Overload:Agibuild.Fulora.IWebViewEnvironmentOptions.UseEphemeralSession
  href: Agibuild.Fulora.IWebViewEnvironmentOptions.html#Agibuild_Fulora_IWebViewEnvironmentOptions_UseEphemeralSession
  name: UseEphemeralSession
  nameWithType: IWebViewEnvironmentOptions.UseEphemeralSession
  fullName: Agibuild.Fulora.IWebViewEnvironmentOptions.UseEphemeralSession
- uid: Agibuild.Fulora.IWebViewEnvironmentOptions.TransparentBackground*
  commentId: Overload:Agibuild.Fulora.IWebViewEnvironmentOptions.TransparentBackground
  href: Agibuild.Fulora.IWebViewEnvironmentOptions.html#Agibuild_Fulora_IWebViewEnvironmentOptions_TransparentBackground
  name: TransparentBackground
  nameWithType: IWebViewEnvironmentOptions.TransparentBackground
  fullName: Agibuild.Fulora.IWebViewEnvironmentOptions.TransparentBackground
- uid: Agibuild.Fulora.IWebViewEnvironmentOptions.CustomSchemes*
  commentId: Overload:Agibuild.Fulora.IWebViewEnvironmentOptions.CustomSchemes
  href: Agibuild.Fulora.IWebViewEnvironmentOptions.html#Agibuild_Fulora_IWebViewEnvironmentOptions_CustomSchemes
  name: CustomSchemes
  nameWithType: IWebViewEnvironmentOptions.CustomSchemes
  fullName: Agibuild.Fulora.IWebViewEnvironmentOptions.CustomSchemes
- uid: System.Collections.Generic.IReadOnlyList{Agibuild.Fulora.CustomSchemeRegistration}
  commentId: T:System.Collections.Generic.IReadOnlyList{Agibuild.Fulora.CustomSchemeRegistration}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IReadOnlyList`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  name: IReadOnlyList<CustomSchemeRegistration>
  nameWithType: IReadOnlyList<CustomSchemeRegistration>
  fullName: System.Collections.Generic.IReadOnlyList<Agibuild.Fulora.CustomSchemeRegistration>
  nameWithType.vb: IReadOnlyList(Of CustomSchemeRegistration)
  fullName.vb: System.Collections.Generic.IReadOnlyList(Of Agibuild.Fulora.CustomSchemeRegistration)
  name.vb: IReadOnlyList(Of CustomSchemeRegistration)
  spec.csharp:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: <
  - uid: Agibuild.Fulora.CustomSchemeRegistration
    name: CustomSchemeRegistration
    href: Agibuild.Fulora.CustomSchemeRegistration.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: (
  - name: Of
  - name: " "
  - uid: Agibuild.Fulora.CustomSchemeRegistration
    name: CustomSchemeRegistration
    href: Agibuild.Fulora.CustomSchemeRegistration.html
  - name: )
- uid: System.Collections.Generic.IReadOnlyList`1
  commentId: T:System.Collections.Generic.IReadOnlyList`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  name: IReadOnlyList<T>
  nameWithType: IReadOnlyList<T>
  fullName: System.Collections.Generic.IReadOnlyList<T>
  nameWithType.vb: IReadOnlyList(Of T)
  fullName.vb: System.Collections.Generic.IReadOnlyList(Of T)
  name.vb: IReadOnlyList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Agibuild.Fulora.IWebViewEnvironmentOptions.PreloadScripts*
  commentId: Overload:Agibuild.Fulora.IWebViewEnvironmentOptions.PreloadScripts
  href: Agibuild.Fulora.IWebViewEnvironmentOptions.html#Agibuild_Fulora_IWebViewEnvironmentOptions_PreloadScripts
  name: PreloadScripts
  nameWithType: IWebViewEnvironmentOptions.PreloadScripts
  fullName: Agibuild.Fulora.IWebViewEnvironmentOptions.PreloadScripts
- uid: System.Collections.Generic.IReadOnlyList{System.String}
  commentId: T:System.Collections.Generic.IReadOnlyList{System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IReadOnlyList`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  name: IReadOnlyList<string>
  nameWithType: IReadOnlyList<string>
  fullName: System.Collections.Generic.IReadOnlyList<string>
  nameWithType.vb: IReadOnlyList(Of String)
  fullName.vb: System.Collections.Generic.IReadOnlyList(Of String)
  name.vb: IReadOnlyList(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
